/**
 * ============================================================
 *  seedProducts.js  —  Database Seeder
 * ============================================================
 *  Seeds the full 90-product catalogue and promo codes into the
 *  MongoDB database.
 *  Run: npm run seed  (from the server folder)
 * ============================================================
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from '../models/Product.js';
import PromoCode from '../models/PromoCode.js';

dotenv.config();

/* ── SVG placeholder helper (matches client/src/data/products.js) ── */
const svg = (title, subtitle, g1, g2, accent, darkText = false) =>
    `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='300' height='400' viewBox='0 0 300 400'><defs><linearGradient id='g' x1='0%25' y1='0%25' x2='100%25' y2='100%25'><stop offset='0%25' stop-color='%23${g1}'/><stop offset='100%25' stop-color='%23${g2}'/></linearGradient></defs><rect width='100%25' height='100%25' fill='url(%23g)'/><text x='50%25' y='48%25' font-family='Outfit,sans-serif' font-weight='800' font-size='20' fill='${darkText ? "%230f172a" : "white"}' text-anchor='middle' dominant-baseline='middle'>${encodeURIComponent(title)}</text><text x='50%25' y='56%25' font-family='Inter,sans-serif' font-size='11' fill='%23${accent}' text-anchor='middle' dominant-baseline='middle'>${encodeURIComponent(subtitle)}</text></svg>`;

// ═══════════════════════════════════════════════════════════════════
//  Full Product Catalogue  (30 × 3 categories = 90 items)
// ═══════════════════════════════════════════════════════════════════

const productsData = [

  // ╔═════════════════════════════════════════════════════════════╗
  // ║                   ELECTRONICS  (30)                       ║
  // ╚═════════════════════════════════════════════════════════════╝

  {
    title: 'Premium Wireless Headphones',
    price: 299.0,
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 124,
    image: 'assets/product-headphones.png',
    images: ['assets/product-headphones.png'],
    description: 'Experience sound in its purest form. Featuring hybrid active noise cancellation, high-fidelity audio drivers, and up to 40 hours of playback.',
    specs: { 'Battery Life': 'Up to 40 Hours', 'Noise Cancellation': 'Hybrid Active ANC (4 Microphones)', 'Connectivity': 'Bluetooth 5.2 / USB-C', 'Weight': '250g' },
    variations: { type: 'color', options: [{ name: 'Deep Blue', value: '#1e3a8a', active: true }, { name: 'Sleek Matte Black', value: '#0f172a', active: false }, { name: 'Silver Frost', value: '#cbd5e1', active: false }] },
    featured: true,
    stock: 55,
  },
  {
    title: 'Ultra-Slim Smart Watch',
    price: 199.0,
    category: 'electronics',
    rating: 4.5,
    reviewsCount: 62,
    image: 'assets/product-smartwatch.png',
    images: ['assets/product-smartwatch.png'],
    description: 'A refined wellness and connectivity assistant on your wrist. Featuring a brilliant always-on AMOLED display and comprehensive health tracking.',
    specs: { 'Display': '1.43" Always-On AMOLED', 'Casing': 'Grade 5 Titanium', 'Battery': 'Up to 7 Days (Typical)', 'Water Resistance': '5 ATM (50 Meters)' },
    variations: { type: 'color', options: [{ name: 'Titanium Black', value: '#0f172a', active: true }, { name: 'Slate Gold', value: '#b45309', active: false }] },
    featured: true,
    stock: 40,
  },
  {
    title: 'Noise-Cancelling Earbuds',
    price: 129.0,
    category: 'electronics',
    rating: 4.4,
    reviewsCount: 51,
    image: 'assets/product-earbuds.png',
    images: ['assets/product-earbuds.png'],
    description: 'True wireless sound meets smart listening. Packed with dual-mic noise cancelling tech, smart touch controls, and IPX5 water resistance.',
    specs: { 'Driver Size': '10mm Dynamic Drivers', 'Waterproof Rating': 'IPX5 Sweat Resistant', 'Playtime': '8 Hours (28 Hours with Case)', 'Charging': 'Wireless Charging / USB-C' },
    variations: { type: 'color', options: [{ name: 'Arctic White', value: '#f8fafc', active: true }, { name: 'Onyx Black', value: '#1e293b', active: false }] },
    featured: false,
    stock: 65,
  },
  {
    title: 'Mechanical Ergonomic Keyboard',
    price: 159.0,
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 78,
    image: 'assets/product-keyboard.png',
    images: ['assets/product-keyboard.png'],
    description: 'A compact 75% mechanical keyboard designed for ergonomic efficiency. Features customized linear hot-swappable switches and sound dampening foams.',
    specs: { 'Form Factor': '75% Layout (84 Keys)', 'Switches': 'Custom Linear Reds (Hot-Swappable)', 'Backlight': 'South-Facing RGB LEDs', 'Keycaps': 'Double-Shot PBT Cherry Profile' },
    variations: { type: 'color', options: [{ name: 'Slate Grey', value: '#64748b', active: true }, { name: 'Chalk White', value: '#f1f5f9', active: false }] },
    featured: false,
    stock: 48,
  },
  {
    title: 'Quantum Noise-Cancelling Headphones',
    price: 349.0,
    category: 'electronics',
    rating: 4.9,
    reviewsCount: 58,
    image: 'assets/product-quantum-headphones.png',
    images: ['assets/product-quantum-headphones.png'],
    description: 'Next-gen active noise cancelling headphones with quantum dot drivers for pristine sound. 30h battery, Bluetooth 5.3.',
    specs: { 'Battery Life': '30 Hours', 'Connectivity': 'Bluetooth 5.3 / USB-C', 'Driver': 'Quantum Dot 40mm', 'Weight': '260g' },
    variations: { type: 'color', options: [{ name: 'Midnight Black', value: '#0f172a', active: true }, { name: 'Arctic Silver', value: '#e5e7eb', active: false }] },
    featured: false,
    stock: 35,
  },
  {
    title: 'Solar-Powered Smartwatch',
    price: 229.0,
    category: 'electronics',
    rating: 4.6,
    reviewsCount: 73,
    image: 'assets/product-solar-watch.png',
    images: ['assets/product-solar-watch.png'],
    description: 'Eco-friendly smartwatch with integrated solar panel, health tracking, and always-on e-ink display. Waterproof to 5 ATM.',
    specs: { 'Display': '1.5" E-ink', 'Battery': 'Solar-Assisted (Up to 14 Days)', 'Sensors': 'HR, SpO2, GPS', 'Water Resistance': '5 ATM' },
    variations: { type: 'color', options: [{ name: 'Eco Green', value: '#065f46', active: true }, { name: 'Space Gray', value: '#374151', active: false }] },
    featured: false,
    stock: 42,
  },
  {
    title: 'AI-Enhanced Gaming Mouse',
    price: 79.0,
    category: 'electronics',
    rating: 4.5,
    reviewsCount: 64,
    image: 'assets/product-gaming-mouse.png',
    images: ['assets/product-gaming-mouse.png'],
    description: 'High-precision ergonomic mouse with AI-driven DPI adjustments, RGB lighting, and programmable macro keys.',
    specs: { 'DPI': '800-16000', 'Buttons': '8 Programmable', 'Connectivity': 'Wired USB-C', 'Weight': '85g' },
    variations: { type: 'color', options: [{ name: 'Neon Purple', value: '#7c3aed', active: true }, { name: 'Carbon Black', value: '#111827', active: false }] },
    featured: false,
    stock: 57,
  },
  {
    title: '4K Ultra HD Drone',
    price: 499.0,
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 42,
    image: svg('4K DRONE', 'AURA SKY', '1e293b', '0f172a', '60a5fa'),
    images: [],
    description: 'Compact 4K drone with foldable arms, GPS stabilization, and 30-minute flight time.',
    specs: { 'Camera': '4K/30fps', 'Flight Time': '30 min', 'Range': '5 km', 'Weight': '250g' },
    variations: { type: 'color', options: [{ name: 'Midnight Black', value: '#0f172a', active: true }, { name: 'Snow White', value: '#f8fafc', active: false }] },
    featured: false,
    stock: 18,
  },
  {
    title: 'Smart Home Hub',
    price: 149.0,
    category: 'electronics',
    rating: 4.7,
    reviewsCount: 55,
    image: svg('SMART HUB', 'AURA HOME', '374151', '111827', 'a78bfa'),
    images: [],
    description: 'Voice-controlled hub that integrates lighting, security cameras, and climate control.',
    specs: { 'Connectivity': 'Wi-Fi, Zigbee, Thread', 'Ports': 'USB-C, Ethernet', 'Power': 'AC Adapter' },
    variations: { type: 'color', options: [{ name: 'Graphite', value: '#1f2937', active: true }] },
    featured: false,
    stock: 31,
  },
  {
    title: 'Wireless Charging Pad',
    price: 39.0,
    category: 'electronics',
    rating: 4.6,
    reviewsCount: 84,
    image: svg('CHARGER', 'WIRELESS 15W', '475569', '1e293b', '38bdf8'),
    images: [],
    description: 'Sleek 15W Qi wireless charger with anti-slip surface and LED indicator.',
    specs: { 'Output': '15W', 'Dimensions': '90x90mm', 'Material': 'Aluminium' },
    variations: { type: 'color', options: [{ name: 'Space Grey', value: '#374151', active: true }, { name: 'Pearl White', value: '#f5f5f5', active: false }] },
    featured: false,
    stock: 47,
  },
  {
    title: 'Portable Bluetooth Speaker',
    price: 89.0,
    category: 'electronics',
    rating: 4.7,
    reviewsCount: 96,
    image: svg('BT SPEAKER', '360 SOUND', '7c3aed', '4c1d95', 'c4b5fd'),
    images: [],
    description: 'Rugged, waterproof Bluetooth speaker with 360° surround sound, deep bass, and 12-hour battery.',
    specs: { 'Output': '20W', 'Battery': '12 Hours', 'Waterproof': 'IP67', 'Weight': '540g' },
    variations: { type: 'color', options: [{ name: 'Obsidian', value: '#1e1b4b', active: true }, { name: 'Sunset Orange', value: '#ea580c', active: false }] },
    featured: true,
    stock: 60,
  },
  {
    title: 'Ultra-Wide Curved Monitor',
    price: 699.0,
    category: 'electronics',
    rating: 4.9,
    reviewsCount: 31,
    image: svg('34 MONITOR', 'ULTRA WIDE QHD', '0c4a6e', '082f49', '38bdf8'),
    images: [],
    description: '34-inch ultra-wide curved monitor with QHD resolution, 165Hz refresh rate, and 1ms response time.',
    specs: { 'Resolution': '3440x1440 QHD', 'Refresh Rate': '165Hz', 'Panel': 'VA Curved 1500R', 'Ports': 'HDMI 2.1, DP 1.4, USB-C' },
    variations: { type: 'color', options: [{ name: 'Matte Black', value: '#0f172a', active: true }] },
    featured: true,
    stock: 14,
  },
  {
    title: 'Smart LED Desk Lamp',
    price: 65.0,
    category: 'electronics',
    rating: 4.5,
    reviewsCount: 47,
    image: svg('DESK LAMP', 'SMART LED', 'f59e0b', '92400e', 'fef3c7'),
    images: [],
    description: 'App-controlled desk lamp with adjustable colour temperature and built-in wireless charger base.',
    specs: { 'Brightness': '800 Lumens', 'Color Temp': '2700K-6500K', 'Power': '12W USB-C', 'Features': 'Qi Charger Base' },
    variations: { type: 'color', options: [{ name: 'White', value: '#f8fafc', active: true }, { name: 'Graphite', value: '#374151', active: false }] },
    featured: false,
    stock: 39,
  },
  {
    title: 'Wireless Gaming Headset',
    price: 179.0,
    category: 'electronics',
    rating: 4.7,
    reviewsCount: 88,
    image: svg('GAMING HEADSET', '7.1 SURROUND', 'dc2626', '7f1d1d', 'fca5a5'),
    images: [],
    description: 'Premium wireless gaming headset with 7.1 virtual surround sound and 24-hour battery life.',
    specs: { 'Audio': '7.1 Virtual Surround', 'Battery': '24 Hours', 'Mic': 'Detachable Boom', 'Weight': '290g' },
    variations: { type: 'color', options: [{ name: 'Crimson', value: '#dc2626', active: true }, { name: 'Stealth Black', value: '#111827', active: false }] },
    featured: false,
    stock: 33,
  },
  {
    title: 'Compact Power Bank 20000mAh',
    price: 49.0,
    category: 'electronics',
    rating: 4.6,
    reviewsCount: 112,
    image: svg('POWER BANK', '20000 mAh', '1e3a8a', '0f172a', '93c5fd'),
    images: [],
    description: 'Slim 20000mAh power bank with 65W PD fast charging. Charges a laptop and phone simultaneously.',
    specs: { 'Capacity': '20000mAh / 72Wh', 'Output': '65W PD', 'Ports': '2x USB-C, 1x USB-A', 'Weight': '380g' },
    variations: { type: 'color', options: [{ name: 'Navy', value: '#1e3a8a', active: true }, { name: 'Silver', value: '#cbd5e1', active: false }] },
    featured: false,
    stock: 72,
  },
  {
    title: 'Smart Fitness Tracker Band',
    price: 59.0,
    category: 'electronics',
    rating: 4.4,
    reviewsCount: 135,
    image: svg('FITNESS BAND', 'AURA FIT', '059669', '064e3b', '6ee7b7'),
    images: [],
    description: 'Sleek fitness tracker with AMOLED display, 24/7 heart-rate monitoring, and 14-day battery life.',
    specs: { 'Display': '1.1" AMOLED', 'Battery': '14 Days', 'Sensors': 'HR, SpO2, Accelerometer', 'Water Resistance': '5 ATM' },
    variations: { type: 'color', options: [{ name: 'Emerald', value: '#059669', active: true }, { name: 'Onyx', value: '#1e293b', active: false }] },
    featured: false,
    stock: 88,
  },
  {
    title: 'Mini Projector 1080p',
    price: 249.0,
    category: 'electronics',
    rating: 4.5,
    reviewsCount: 39,
    image: svg('PROJECTOR', '1080P HDR', '78350f', '422006', 'fde68a'),
    images: [],
    description: 'Pocket-sized 1080p projector with auto-keystone, built-in speakers, and screen mirroring.',
    specs: { 'Resolution': '1920x1080', 'Brightness': '400 ANSI Lumens', 'Throw': '1.2:1', 'Battery': '2.5 Hours' },
    variations: { type: 'color', options: [{ name: 'Cream', value: '#fef9ef', active: true }, { name: 'Slate', value: '#334155', active: false }] },
    featured: false,
    stock: 22,
  },
  {
    title: 'USB-C Docking Station',
    price: 119.0,
    category: 'electronics',
    rating: 4.7,
    reviewsCount: 53,
    image: svg('DOCK STATION', 'USB-C 12-IN-1', '334155', '0f172a', '94a3b8'),
    images: [],
    description: '12-in-1 USB-C hub with dual HDMI 4K, Ethernet, and 100W PD pass-through.',
    specs: { 'Ports': '12', 'Video Out': 'Dual HDMI 4K@60Hz', 'PD Pass-through': '100W', 'Material': 'Aluminium' },
    variations: { type: 'color', options: [{ name: 'Space Grey', value: '#334155', active: true }] },
    featured: false,
    stock: 41,
  },
  {
    title: 'Smart Air Purifier',
    price: 189.0,
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 66,
    image: svg('AIR PURIFIER', 'HEPA H13', 'e0f2fe', 'bae6fd', '0284c7', true),
    images: [],
    description: 'Whisper-quiet smart air purifier with H13 True HEPA filter and real-time PM2.5 sensor.',
    specs: { 'Filter': 'H13 True HEPA + Carbon', 'Coverage': '45m2', 'Noise': '22-48 dB', 'Smart': 'Wi-Fi / App' },
    variations: { type: 'color', options: [{ name: 'Arctic White', value: '#f8fafc', active: true }, { name: 'Charcoal', value: '#374151', active: false }] },
    featured: false,
    stock: 28,
  },
  {
    title: 'Retro Vinyl Turntable',
    price: 199.0,
    category: 'electronics',
    rating: 4.6,
    reviewsCount: 44,
    image: svg('TURNTABLE', 'VINYL RETRO', '78350f', '451a03', 'd97706'),
    images: [],
    description: 'Belt-drive turntable with built-in phono preamp, Bluetooth streaming, and walnut-veneer finish.',
    specs: { 'Drive': 'Belt-Drive', 'Cartridge': 'AT3600L', 'Outputs': 'RCA, Bluetooth 5.0', 'Finish': 'Walnut Veneer' },
    variations: { type: 'color', options: [{ name: 'Walnut', value: '#78350f', active: true }, { name: 'Piano Black', value: '#0f172a', active: false }] },
    featured: false,
    stock: 19,
  },
  {
    title: 'E-Reader 7" Paperwhite',
    price: 139.0,
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 71,
    image: svg('E-READER', 'PAPERWHITE 7', '1e293b', '0f172a', 'e2e8f0'),
    images: [],
    description: '7-inch glare-free e-ink display with adjustable warm light and 32GB storage.',
    specs: { 'Display': '7" E-Ink 300ppi', 'Storage': '32 GB', 'Battery': 'Up to 10 Weeks', 'Water': 'IPX8' },
    variations: { type: 'color', options: [{ name: 'Black', value: '#0f172a', active: true }, { name: 'Sage', value: '#4d7c0f', active: false }] },
    featured: false,
    stock: 55,
  },
  {
    title: 'Webcam 4K HDR Pro',
    price: 109.0,
    category: 'electronics',
    rating: 4.5,
    reviewsCount: 38,
    image: svg('WEBCAM 4K', 'HDR PRO', '3730a3', '1e1b4b', 'a5b4fc'),
    images: [],
    description: '4K HDR webcam with auto-framing, dual noise-cancelling mics, and privacy shutter.',
    specs: { 'Resolution': '4K / 30fps', 'FOV': '82 deg', 'Mic': 'Dual Omnidirectional', 'Mount': 'Universal Clip' },
    variations: { type: 'color', options: [{ name: 'Matte Black', value: '#0f172a', active: true }] },
    featured: false,
    stock: 36,
  },
  {
    title: 'Noise Machine & Night Light',
    price: 45.0,
    category: 'electronics',
    rating: 4.7,
    reviewsCount: 92,
    image: svg('NOISE MACHINE', 'SLEEP AID', '4c1d95', '2e1065', 'c4b5fd'),
    images: [],
    description: 'Compact sound machine with 30 soothing soundscapes and a soft RGB night-light.',
    specs: { 'Sounds': '30 Soundscapes', 'Light': 'Warm RGB LED', 'Timer': '30/60/90 min', 'Power': 'USB-C' },
    variations: { type: 'color', options: [{ name: 'Cloud', value: '#ede9fe', active: true }, { name: 'Midnight', value: '#1e1b4b', active: false }] },
    featured: false,
    stock: 64,
  },
  {
    title: 'Smart Plug 4-Pack',
    price: 35.0,
    category: 'electronics',
    rating: 4.4,
    reviewsCount: 155,
    image: svg('SMART PLUG', '4-PACK Wi-Fi', '065f46', '022c22', '34d399'),
    images: [],
    description: 'Wi-Fi smart plugs (4-pack) with energy monitoring and voice control. No hub required.',
    specs: { 'Connectivity': 'Wi-Fi 2.4GHz', 'Max Load': '15A / 1800W', 'Voice': 'Alexa, Google, Siri', 'Qty': '4 Pack' },
    variations: { type: 'color', options: [{ name: 'White', value: '#f8fafc', active: true }] },
    featured: false,
    stock: 120,
  },
  {
    title: 'Digital Drawing Tablet',
    price: 259.0,
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 49,
    image: svg('DRAW TABLET', 'PEN DISPLAY', 'be123c', '881337', 'fda4af'),
    images: [],
    description: '10-inch pen display with 8192 pressure levels and battery-free stylus.',
    specs: { 'Display': '10.1" FHD IPS', 'Pressure': '8192 Levels', 'Color': '120% sRGB', 'Stylus': 'Battery-Free' },
    variations: { type: 'color', options: [{ name: 'Cosmos Black', value: '#1c1917', active: true }] },
    featured: false,
    stock: 25,
  },
  {
    title: 'Mesh Wi-Fi System (3-Pack)',
    price: 229.0,
    category: 'electronics',
    rating: 4.7,
    reviewsCount: 67,
    image: svg('MESH WI-FI', 'AX5400 3-PACK', '0891b2', '164e63', '67e8f9'),
    images: [],
    description: 'Tri-band Wi-Fi 6E mesh system covering up to 6000 sq ft with seamless roaming.',
    specs: { 'Speed': 'AX5400', 'Coverage': '6000 sq ft', 'Bands': 'Tri-Band', 'Ports': '2x Gigabit per Node' },
    variations: { type: 'color', options: [{ name: 'White', value: '#f0fdfa', active: true }] },
    featured: false,
    stock: 30,
  },
  {
    title: 'Portable SSD 2TB',
    price: 159.0,
    category: 'electronics',
    rating: 4.9,
    reviewsCount: 83,
    image: svg('PORTABLE SSD', '2TB USB-C', '475569', '1e293b', 'cbd5e1'),
    images: [],
    description: 'Pocket-sized 2TB NVMe SSD with up to 2000MB/s read speeds. IP65 rated.',
    specs: { 'Capacity': '2 TB', 'Speed': '2000 MB/s Read', 'Interface': 'USB 3.2 Gen 2x2', 'Protection': 'IP65, 3m Drop' },
    variations: { type: 'color', options: [{ name: 'Titanium Grey', value: '#475569', active: true }, { name: 'Indigo', value: '#4338ca', active: false }] },
    featured: true,
    stock: 50,
  },
  {
    title: 'Smart Doorbell Camera',
    price: 129.0,
    category: 'electronics',
    rating: 4.6,
    reviewsCount: 101,
    image: svg('DOORBELL CAM', '2K HDR', '1c1917', '0c0a09', 'a8a29e'),
    images: [],
    description: '2K HDR video doorbell with person detection, two-way audio, and night vision.',
    specs: { 'Video': '2K HDR', 'FOV': '160 deg Diagonal', 'Audio': 'Two-Way', 'Storage': 'Cloud + microSD' },
    variations: { type: 'color', options: [{ name: 'Satin Nickel', value: '#a8a29e', active: true }, { name: 'Venetian Bronze', value: '#78350f', active: false }] },
    featured: false,
    stock: 44,
  },
  {
    title: 'Clip-On Ring Light 10"',
    price: 29.0,
    category: 'electronics',
    rating: 4.3,
    reviewsCount: 118,
    image: svg('RING LIGHT', '10 CLIP-ON', 'f43f5e', '9f1239', 'fecdd3'),
    images: [],
    description: '10-inch clip-on ring light with 3 colour modes and 10 brightness levels.',
    specs: { 'Size': '10 inches', 'Modes': 'Warm / Neutral / Cool', 'Power': 'USB', 'Arm': 'Flexible Gooseneck' },
    variations: { type: 'color', options: [{ name: 'Black', value: '#0f172a', active: true }, { name: 'White', value: '#f8fafc', active: false }] },
    featured: false,
    stock: 78,
  },
  {
    title: 'Smart Body Composition Scale',
    price: 55.0,
    category: 'electronics',
    rating: 4.5,
    reviewsCount: 74,
    image: svg('SMART SCALE', 'BODY COMP', '0d9488', '115e59', '99f6e4'),
    images: [],
    description: 'Wi-Fi smart scale measuring weight, BMI, body fat, muscle mass, and 10 other metrics.',
    specs: { 'Metrics': '13 Body Measurements', 'Connectivity': 'Wi-Fi + Bluetooth', 'Users': 'Unlimited Profiles', 'Surface': 'Tempered Glass' },
    variations: { type: 'color', options: [{ name: 'White', value: '#f0fdfa', active: true }, { name: 'Black', value: '#0f172a', active: false }] },
    featured: false,
    stock: 53,
  },

  // ╔═════════════════════════════════════════════════════════════╗
  // ║                    CLOTHING  (30)                         ║
  // ╚═════════════════════════════════════════════════════════════╝

  {
    title: 'Minimalist Windbreaker Jacket',
    price: 149.0,
    category: 'clothing',
    rating: 4.6,
    reviewsCount: 89,
    image: 'assets/product-jacket.png',
    images: ['assets/product-jacket.png'],
    description: 'A sleek wind-and-water-resistant shell designed for metropolitan exploration.',
    specs: { 'Material': '100% Recycled Ripstop Nylon', 'Waterproofing': 'DWR Coating', 'Pockets': '2 Exterior Zip, 1 Interior', 'Fit': 'Regular Modern Fit' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: true,
    stock: 45,
  },
  {
    title: 'Waterproof Urban Backpack',
    price: 89.0,
    category: 'clothing',
    rating: 4.7,
    reviewsCount: 145,
    image: 'assets/product-backpack.png',
    images: ['assets/product-backpack.png'],
    description: 'Engineered for commuter convenience with roll-top enclosure and 16" laptop sleeve.',
    specs: { 'Capacity': '22 Liters', 'Laptop Sleeve': 'Up to 16" MacBook Pro', 'Material': '900D TPU Recycled Polyester', 'Weight': '850g' },
    variations: { type: 'size', options: ['Standard (22L)', 'Large (30L)'] },
    featured: true,
    stock: 38,
  },
  {
    title: 'Oversized Organic Cotton Tee',
    price: 45.0,
    category: 'clothing',
    rating: 4.9,
    reviewsCount: 210,
    image: 'assets/product-tee.png',
    images: ['assets/product-tee.png'],
    description: 'Cut from heavy, 280gsm organic cotton jersey with boxy dropped-shoulder silhouette.',
    specs: { 'Material': '100% GOTS Certified Organic Cotton', 'Fabric Weight': '280 GSM Heavyweight', 'Fit': 'Oversized Boxy Fit', 'Care': 'Machine Wash Cold, Hang Dry' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 95,
  },
  {
    title: 'Recycled Wool Knit Sweater',
    price: 120.0,
    category: 'clothing',
    rating: 4.7,
    reviewsCount: 93,
    image: 'assets/product-sweater.png',
    images: ['assets/product-sweater.png'],
    description: 'A beautiful midweight fisherman ribbed knit from recycled merino wool and cashmere.',
    specs: { 'Material': '70% Recycled Merino Wool, 30% Recycled Cashmere', 'Knit Pattern': 'Traditional Ribbed Fisherman Knit', 'Fit': 'Relaxed Casual', 'Weight': '450g' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 40,
  },
  {
    title: 'Organic Hemp Hoodie',
    price: 68.0,
    category: 'clothing',
    rating: 4.8,
    reviewsCount: 112,
    image: 'assets/product-hoodie.png',
    images: ['assets/product-hoodie.png'],
    description: 'Soft, breathable hoodie crafted from 100% organic hemp with eco-friendly dye.',
    specs: { 'Material': '100% Organic Hemp', 'Weight': '350g', 'Fit': 'Relaxed', 'Care': 'Machine Wash Cold' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL', 'XXL'] },
    featured: true,
    stock: 48,
  },
  {
    title: 'Recycled Denim Jeans',
    price: 85.0,
    category: 'clothing',
    rating: 4.6,
    reviewsCount: 95,
    image: 'assets/product-jeans.png',
    images: ['assets/product-jeans.png'],
    description: 'Sustainable denim jeans made from post-consumer recycled cotton.',
    specs: { 'Material': '70% Recycled Cotton, 30% Elastane', 'Fit': 'Straight', 'Rise': 'Mid', 'Care': 'Machine Wash Warm' },
    variations: { type: 'size', options: ['28', '30', '32', '34', '36'] },
    featured: false,
    stock: 63,
  },
  {
    title: 'Premium Leather Belt',
    price: 45.0,
    category: 'clothing',
    rating: 4.7,
    reviewsCount: 54,
    image: 'assets/product-belt.png',
    images: ['assets/product-belt.png'],
    description: 'Hand-stitched full-grain leather belt with polished brass buckle.',
    specs: { 'Material': 'Full-Grain Leather', 'Buckle': 'Polished Brass', 'Width': '3.5 cm' },
    variations: { type: 'color', options: [{ name: 'Classic Brown', value: '#7b341e', active: true }, { name: 'Deep Black', value: '#111827', active: false }] },
    featured: false,
    stock: 71,
  },
  {
    title: 'Eco-Friendly Bamboo Sunglasses',
    price: 59.0,
    category: 'clothing',
    rating: 4.8,
    reviewsCount: 37,
    image: svg('SUNGLASSES', 'BAMBOO UV400', 'a9917b', '5d4037', 'fef3c7'),
    images: [],
    description: 'Lightweight bamboo frame sunglasses with polarized lenses and UV-400 protection.',
    specs: { 'Frame': 'Bamboo', 'Lens': 'Polarized', 'UV': '400' },
    variations: { type: 'color', options: [{ name: 'Natural', value: '#a9917b', active: true }, { name: 'Dark Walnut', value: '#5d4037', active: false }] },
    featured: true,
    stock: 22,
  },
  {
    title: 'Premium Cashmere Scarf',
    price: 79.0,
    category: 'clothing',
    rating: 4.9,
    reviewsCount: 29,
    image: svg('CASHMERE SCARF', 'LUXURY KNIT', 'e2e8f0', '94a3b8', '475569', true),
    images: [],
    description: 'Luxuriously soft 100% cashmere scarf. Warm, breathable, and perfect for layering.',
    specs: { 'Material': '100% Cashmere', 'Length': '180cm', 'Width': '30cm' },
    variations: { type: 'color', options: [{ name: 'Ivory', value: '#fafafa', active: true }, { name: 'Charcoal', value: '#374151', active: false }] },
    featured: false,
    stock: 34,
  },
  {
    title: 'Minimalist Leather Backpack',
    price: 129.0,
    category: 'clothing',
    rating: 4.7,
    reviewsCount: 48,
    image: svg('LEATHER PACK', 'VEG-TANNED', '8d5524', '5c2d0e', 'fde68a'),
    images: [],
    description: 'Sleek backpack from vegetable-tanned leather with padded laptop sleeve.',
    specs: { 'Material': 'Vegetable-tanned Leather', 'Capacity': '20L', 'Laptop Sleeve': '15"' },
    variations: { type: 'color', options: [{ name: 'Chestnut', value: '#8d5524', active: true }, { name: 'Midnight', value: '#0f172a', active: false }] },
    featured: false,
    stock: 27,
  },
  {
    title: 'Silk Blend Evening Gown',
    price: 299.0,
    category: 'clothing',
    rating: 4.9,
    reviewsCount: 22,
    image: svg('EVENING GOWN', 'SILK BLEND', '831843', '500724', 'f9a8d4'),
    images: [],
    description: 'Luxurious silk-blend gown with a flowing silhouette and subtle shimmer.',
    specs: { 'Material': '70% Silk, 30% Polyester', 'Length': 'Floor-length', 'Fit': 'Tailored A-Line', 'Care': 'Dry Clean Only' },
    variations: { type: 'size', options: ['XS', 'S', 'M', 'L'] },
    featured: true,
    stock: 12,
  },
  {
    title: 'Technical Cargo Pants',
    price: 95.0,
    category: 'clothing',
    rating: 4.6,
    reviewsCount: 77,
    image: svg('CARGO PANTS', 'TECH FABRIC', '374151', '111827', '9ca3af'),
    images: [],
    description: 'Water-repellent technical cargo pants with articulated knees and 6 pockets.',
    specs: { 'Material': 'Nylon Ripstop DWR', 'Pockets': '6 (2 Hidden Zip)', 'Fit': 'Relaxed Taper', 'Care': 'Machine Wash' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 55,
  },
  {
    title: 'Linen Button-Down Shirt',
    price: 75.0,
    category: 'clothing',
    rating: 4.7,
    reviewsCount: 63,
    image: svg('LINEN SHIRT', 'SUMMER CLASSIC', 'e0f2fe', 'bae6fd', '0369a1', true),
    images: [],
    description: 'Relaxed-fit linen button-down in breezy sky blue with mother-of-pearl buttons.',
    specs: { 'Material': '100% European Linen', 'Fit': 'Relaxed', 'Buttons': 'Mother-of-Pearl', 'Care': 'Machine Wash, Hang Dry' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 42,
  },
  {
    title: 'Merino Wool Beanie',
    price: 35.0,
    category: 'clothing',
    rating: 4.8,
    reviewsCount: 128,
    image: svg('MERINO BEANIE', 'RIBBED KNIT', '1c1917', '0c0a09', 'a8a29e'),
    images: [],
    description: 'Classic ribbed beanie from soft Australian merino wool. Double-layer construction.',
    specs: { 'Material': '100% Merino Wool', 'Knit': 'Ribbed Double-Layer', 'Size': 'One Size Fits All', 'Weight': '65g' },
    variations: { type: 'color', options: [{ name: 'Charcoal', value: '#1c1917', active: true }, { name: 'Oatmeal', value: '#d6d3d1', active: false }, { name: 'Navy', value: '#1e3a8a', active: false }] },
    featured: false,
    stock: 80,
  },
  {
    title: 'Water-Resistant Puffer Vest',
    price: 110.0,
    category: 'clothing',
    rating: 4.6,
    reviewsCount: 56,
    image: svg('PUFFER VEST', 'INSULATED', '1e3a8a', '172554', '93c5fd'),
    images: [],
    description: 'Lightweight quilted puffer vest with recycled synthetic down insulation.',
    specs: { 'Material': 'Recycled Nylon Shell', 'Insulation': 'Recycled Synthetic Down', 'Weight': '280g', 'Water': 'DWR Coating' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 37,
  },
  {
    title: 'Stretch Chino Shorts',
    price: 55.0,
    category: 'clothing',
    rating: 4.5,
    reviewsCount: 88,
    image: svg('CHINO SHORTS', 'STRETCH FIT', '78350f', '451a03', 'fbbf24'),
    images: [],
    description: 'Classic 7-inch chino shorts with 2% stretch. Garment-dyed for a lived-in look.',
    specs: { 'Material': '98% Cotton, 2% Elastane', 'Inseam': '7 inches', 'Fit': 'Slim', 'Care': 'Machine Wash' },
    variations: { type: 'size', options: ['28', '30', '32', '34', '36'] },
    featured: false,
    stock: 70,
  },
  {
    title: 'Quilted Field Jacket',
    price: 179.0,
    category: 'clothing',
    rating: 4.8,
    reviewsCount: 41,
    image: svg('FIELD JACKET', 'QUILTED LINING', '365314', '1a2e05', 'a3e635'),
    images: [],
    description: 'Heritage field jacket with diamond-quilted lining and waxed cotton shell.',
    specs: { 'Material': 'Waxed Cotton Shell', 'Lining': 'Quilted Polyester', 'Pockets': '4 Flap + 2 Interior', 'Fit': 'Regular' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL', 'XXL'] },
    featured: true,
    stock: 20,
  },
  {
    title: 'Bamboo Fibre Polo Shirt',
    price: 52.0,
    category: 'clothing',
    rating: 4.6,
    reviewsCount: 73,
    image: svg('BAMBOO POLO', 'ECO FIBRE', '065f46', '022c22', '6ee7b7'),
    images: [],
    description: 'Ultra-soft polo from bamboo fibre blend. Naturally antimicrobial and thermoregulating.',
    specs: { 'Material': '70% Bamboo, 30% Organic Cotton', 'Fit': 'Classic', 'Features': 'Anti-Microbial, UV-Protective', 'Care': 'Machine Wash Cold' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 58,
  },
  {
    title: 'Tailored Wool Blazer',
    price: 225.0,
    category: 'clothing',
    rating: 4.9,
    reviewsCount: 34,
    image: svg('WOOL BLAZER', 'TAILORED FIT', '1c1917', '292524', '78716c'),
    images: [],
    description: 'Half-canvas wool blazer with pick-stitched lapels and genuine horn buttons.',
    specs: { 'Material': '100% Italian Wool', 'Construction': 'Half-Canvas', 'Buttons': 'Genuine Horn', 'Lining': 'Bemberg Cupro' },
    variations: { type: 'size', options: ['36R', '38R', '40R', '42R', '44R'] },
    featured: true,
    stock: 15,
  },
  {
    title: 'Performance Running Tights',
    price: 65.0,
    category: 'clothing',
    rating: 4.5,
    reviewsCount: 91,
    image: svg('RUN TIGHTS', 'COMPRESSION', '0f172a', '020617', '818cf8'),
    images: [],
    description: 'High-waisted compression running tights with side phone pocket and reflective details.',
    specs: { 'Material': '78% Nylon, 22% Elastane', 'Features': 'Compression, Reflective', 'Pocket': 'Side Phone Pocket', 'Care': 'Machine Wash Cold' },
    variations: { type: 'size', options: ['XS', 'S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 62,
  },
  {
    title: 'Heavyweight Flannel Shirt',
    price: 72.0,
    category: 'clothing',
    rating: 4.7,
    reviewsCount: 65,
    image: svg('FLANNEL SHIRT', 'BRUSHED TWILL', '7f1d1d', '450a0a', 'fca5a5'),
    images: [],
    description: 'Thick brushed-cotton flannel shirt in classic buffalo check.',
    specs: { 'Material': '100% Brushed Cotton Flannel', 'Weight': '280 GSM', 'Fit': 'Relaxed', 'Care': 'Machine Wash Warm' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL', 'XXL'] },
    featured: false,
    stock: 47,
  },
  {
    title: 'Reversible Down Jacket',
    price: 199.0,
    category: 'clothing',
    rating: 4.8,
    reviewsCount: 38,
    image: svg('DOWN JACKET', 'REVERSIBLE', '1e293b', '0f172a', '64748b'),
    images: [],
    description: 'Two jackets in one — reversible down jacket with 700-fill RDS-certified down.',
    specs: { 'Material': 'Recycled Nylon', 'Fill': '700-Fill RDS Down', 'Weight': '380g', 'Water': 'DWR Coating' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 25,
  },
  {
    title: 'Classic Leather Watch Strap',
    price: 39.0,
    category: 'clothing',
    rating: 4.6,
    reviewsCount: 44,
    image: svg('WATCH STRAP', 'ITALIAN LEATHER', '92400e', '451a03', 'd97706'),
    images: [],
    description: 'Handcrafted Italian calfskin watch strap with quick-release spring bars.',
    specs: { 'Material': 'Italian Calfskin', 'Width': '20mm / 22mm', 'Length': '120/75mm', 'Clasp': 'Stainless Steel' },
    variations: { type: 'color', options: [{ name: 'Cognac', value: '#92400e', active: true }, { name: 'Black', value: '#1c1917', active: false }] },
    featured: false,
    stock: 50,
  },
  {
    title: 'Organic Cotton Joggers',
    price: 62.0,
    category: 'clothing',
    rating: 4.7,
    reviewsCount: 82,
    image: svg('JOGGERS', 'ORGANIC COTTON', '334155', '1e293b', '94a3b8'),
    images: [],
    description: 'Relaxed-fit joggers in heavy organic cotton terry. Ribbed cuffs and drawstring waist.',
    specs: { 'Material': '100% Organic Cotton Terry', 'Weight': '340 GSM', 'Fit': 'Relaxed Taper', 'Care': 'Machine Wash Cold' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 73,
  },
  {
    title: 'UV-Protection Bucket Hat',
    price: 32.0,
    category: 'clothing',
    rating: 4.4,
    reviewsCount: 59,
    image: svg('BUCKET HAT', 'UPF 50+', '0c4a6e', '082f49', '7dd3fc'),
    images: [],
    description: 'Lightweight bucket hat with UPF 50+ sun protection and quick-dry nylon.',
    specs: { 'Material': 'Quick-Dry Nylon', 'UPF': '50+', 'Size': 'S/M, L/XL', 'Features': 'Packable, Chin Strap' },
    variations: { type: 'color', options: [{ name: 'Stone', value: '#a8a29e', active: true }, { name: 'Navy', value: '#1e3a8a', active: false }, { name: 'Olive', value: '#365314', active: false }] },
    featured: false,
    stock: 66,
  },
  {
    title: 'Stretch Denim Jacket',
    price: 105.0,
    category: 'clothing',
    rating: 4.6,
    reviewsCount: 51,
    image: svg('DENIM JACKET', 'STRETCH FIT', '1e40af', '1e3a8a', '93c5fd'),
    images: [],
    description: 'Classic trucker-style denim jacket with 2% stretch for comfort.',
    specs: { 'Material': '98% Cotton, 2% Elastane', 'Wash': 'Medium Indigo', 'Fit': 'Slim', 'Buttons': 'Brass' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 39,
  },
  {
    title: 'Wool-Blend Overcoat',
    price: 275.0,
    category: 'clothing',
    rating: 4.9,
    reviewsCount: 27,
    image: svg('OVERCOAT', 'WOOL BLEND', '292524', '1c1917', '78716c'),
    images: [],
    description: 'Timeless single-breasted overcoat in Italian wool-cashmere blend.',
    specs: { 'Material': '80% Wool, 20% Cashmere', 'Length': 'Knee-Length', 'Lining': 'Viscose Half-Lining', 'Fit': 'Regular' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: true,
    stock: 14,
  },
  {
    title: 'Canvas Tote Bag',
    price: 38.0,
    category: 'clothing',
    rating: 4.5,
    reviewsCount: 97,
    image: svg('CANVAS TOTE', 'HEAVY DUTY', '78350f', '422006', 'fde68a'),
    images: [],
    description: 'Extra-thick 18oz canvas tote with leather handles and interior pocket.',
    specs: { 'Material': '18oz Canvas + Leather Handles', 'Dimensions': '40x35x12 cm', 'Pockets': '1 Interior Zip', 'Weight': '420g' },
    variations: { type: 'color', options: [{ name: 'Natural', value: '#fef3c7', active: true }, { name: 'Olive', value: '#365314', active: false }] },
    featured: false,
    stock: 85,
  },
  {
    title: 'Thermal Base Layer Top',
    price: 48.0,
    category: 'clothing',
    rating: 4.6,
    reviewsCount: 58,
    image: svg('BASE LAYER', 'THERMAL MERINO', '0f172a', '020617', '64748b'),
    images: [],
    description: 'Midweight merino wool base-layer top with flatlock seams and thumb loops.',
    specs: { 'Material': '100% Merino Wool (200gsm)', 'Fit': 'Slim Athletic', 'Features': 'Flatlock Seams, Thumb Loops', 'Care': 'Machine Wash Wool Cycle' },
    variations: { type: 'size', options: ['S', 'M', 'L', 'XL'] },
    featured: false,
    stock: 44,
  },
  {
    title: 'Printed Silk Pocket Square',
    price: 28.0,
    category: 'clothing',
    rating: 4.7,
    reviewsCount: 41,
    image: svg('POCKET SQUARE', 'SILK PRINT', '4c1d95', '2e1065', 'c4b5fd'),
    images: [],
    description: 'Hand-rolled Italian silk pocket square with geometric print.',
    specs: { 'Material': '100% Italian Silk', 'Size': '33x33 cm', 'Edge': 'Hand-Rolled', 'Pattern': 'Geometric' },
    variations: { type: 'color', options: [{ name: 'Purple Geo', value: '#4c1d95', active: true }, { name: 'Navy Paisley', value: '#1e3a8a', active: false }, { name: 'Burgundy Dot', value: '#7f1d1d', active: false }] },
    featured: false,
    stock: 60,
  },

  // ╔═════════════════════════════════════════════════════════════╗
  // ║                    FOOTWEAR  (30)                         ║
  // ╚═════════════════════════════════════════════════════════════╝

  {
    title: 'Aura Runner Pro Sneaker',
    price: 189.0,
    category: 'footwear',
    rating: 4.9,
    reviewsCount: 312,
    image: 'assets/product-sneaker.png',
    images: ['assets/product-sneaker.png'],
    description: 'Performance-engineered sneaker built for daily training and urban style.',
    specs: { 'Upper Material': 'Engineered Mesh Knit', 'Sole Material': 'EVA Foam + Rubber Outsole', 'Lacing System': 'Traditional Lace-Up', 'Drop': '8mm Heel-to-Toe Drop', 'Weight': '285g (EU 42)', 'Closure': 'Lace-Up' },
    variations: { type: 'color', options: [{ name: 'Midnight Ink', value: '#1e293b', active: true }, { name: 'Cloud White', value: '#f1f5f9', active: false }, { name: 'Ember Red', value: '#dc2626', active: false }] },
    featured: true,
    stock: 42,
    stockBySize: { '39': 0, '40': 8, '41': 12, '42': 15, '43': 7, '44': 0, '45': 3 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'EVA Foam Compound + Vulcanised Rubber Outsole',
    upperMaterial: 'Breathable Engineered Mesh Knit',
  },
  {
    title: 'Heritage Leather Oxford',
    price: 245.0,
    category: 'footwear',
    rating: 4.7,
    reviewsCount: 178,
    image: 'assets/product-oxford.png',
    images: ['assets/product-oxford.png'],
    description: 'A timeless cap-toe Oxford crafted from premium full-grain vegetable-tanned leather.',
    specs: { 'Upper Material': 'Full-Grain Vegetable-Tanned Leather', 'Sole Material': 'Leather Insole + Rubber Heel', 'Construction': 'Goodyear Welt (Resoleable)', 'Toe Shape': 'Cap-Toe Oxford', 'Lining': 'Natural Leather Lining', 'Closure': 'Lace-Up' },
    variations: { type: 'color', options: [{ name: 'Chestnut Brown', value: '#92400e', active: true }, { name: 'Jet Black', value: '#0f172a', active: false }] },
    featured: true,
    stock: 27,
    stockBySize: { '40': 4, '41': 6, '42': 9, '43': 0, '44': 5, '45': 3 },
    ukSizes: [6, 7, 8, 9, 10, 11],
    soleMaterial: 'Leather Insole + Stacked Leather Heel with Rubber Top-Piece',
    upperMaterial: 'Premium Full-Grain Vegetable-Tanned Leather',
  },
  {
    title: "Runner's Trail Sneakers",
    price: 132.0,
    category: 'footwear',
    rating: 4.8,
    reviewsCount: 140,
    image: svg('TRAIL SNEAKER', 'ALL-TERRAIN', '065f46', '022c22', '6ee7b7'),
    images: [],
    description: 'All-terrain sneaker with breathable mesh upper and grippy rubber outsole.',
    specs: { 'Upper Material': 'Mesh + TPU', 'Sole Material': 'Rubber', 'Drop': '10mm', 'Weight': '290g' },
    variations: { type: 'color', options: [{ name: 'Forest Green', value: '#065f46', active: true }, { name: 'Desert Sand', value: '#d97706', active: false }] },
    featured: true,
    stock: 38,
    stockBySize: { '39': 2, '40': 5, '41': 8, '42': 12, '43': 6, '44': 3, '45': 2 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Multi-Terrain Rubber Outsole',
    upperMaterial: 'Breathable Mesh + TPU Reinforcements',
  },
  {
    title: 'Classic Suede Loafers',
    price: 149.0,
    category: 'footwear',
    rating: 4.7,
    reviewsCount: 82,
    image: svg('SUEDE LOAFER', 'CLASSIC SLIP-ON', '1e3a8a', '172554', '93c5fd'),
    images: [],
    description: 'Slip-on loafers crafted from premium suede with cushioned footbed.',
    specs: { 'Upper Material': 'Suede', 'Sole Material': 'Rubber', 'Closure': 'Slip-On', 'Weight': '260g' },
    variations: { type: 'color', options: [{ name: 'Vintage Navy', value: '#1e3a8a', active: true }, { name: 'Warm Taupe', value: '#9c7c38', active: false }] },
    featured: false,
    stock: 27,
    stockBySize: { '39': 1, '40': 4, '41': 7, '42': 9, '43': 3, '44': 2, '45': 1 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Flexible Rubber Outsole',
    upperMaterial: 'Premium Italian Suede',
  },
  {
    title: 'High-Top Canvas Skate Shoes',
    price: 79.0,
    category: 'footwear',
    rating: 4.5,
    reviewsCount: 61,
    image: svg('SKATE HI-TOP', 'CANVAS', '0f172a', '020617', '64748b'),
    images: [],
    description: 'Durable canvas high-top shoes with reinforced toe and grippy rubber sole.',
    specs: { 'Upper Material': 'Canvas', 'Sole Material': 'Rubber', 'Closure': 'Lace-Up', 'Weight': '310g' },
    variations: { type: 'color', options: [{ name: 'Jet Black', value: '#0f172a', active: true }, { name: 'Crimson Red', value: '#b91c1c', active: false }] },
    featured: false,
    stock: 44,
    stockBySize: { '39': 0, '40': 6, '41': 10, '42': 12, '43': 8, '44': 4, '45': 4 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Vulcanised Rubber',
    upperMaterial: 'Heavy-Duty Canvas',
  },
  {
    title: 'Luxury Velvet Dress Shoes',
    price: 219.0,
    category: 'footwear',
    rating: 4.9,
    reviewsCount: 37,
    image: svg('VELVET DRESS', 'LUXURY', '1e40af', '172554', '93c5fd'),
    images: [],
    description: 'Elegant velvet dress shoes with silk lining and polished leather sole.',
    specs: { 'Upper Material': 'Velvet', 'Sole Material': 'Polished Leather', 'Closure': 'Lace-Up', 'Weight': '330g' },
    variations: { type: 'color', options: [{ name: 'Royal Blue', value: '#1e40af', active: true }, { name: 'Deep Burgundy', value: '#7f1d1d', active: false }] },
    featured: true,
    stock: 22,
    stockBySize: { '39': 1, '40': 3, '41': 5, '42': 8, '43': 2, '44': 1, '45': 2 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Polished Leather Sole',
    upperMaterial: 'Italian Velvet with Silk Lining',
  },
  {
    title: 'Trail Running Shoes Pro',
    price: 149.0,
    category: 'footwear',
    rating: 4.8,
    reviewsCount: 58,
    image: svg('TRAIL PRO', 'ROCK PLATE', '365314', '1a2e05', '84cc16'),
    images: [],
    description: 'High-grip trail runners with rock-plate protection and responsive cushioning.',
    specs: { 'Upper Material': 'Engineered Mesh', 'Sole Material': 'Vibram', 'Drop': '8mm', 'Weight': '295g' },
    variations: { type: 'color', options: [{ name: 'Forest Moss', value: '#065f46', active: true }, { name: 'Sandstone', value: '#d97706', active: false }] },
    featured: true,
    stock: 31,
    stockBySize: { '39': 2, '40': 4, '41': 7, '42': 9, '43': 5, '44': 3, '45': 1 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Vibram Megagrip',
    upperMaterial: 'Engineered Mesh with TPU Cage',
  },
  {
    title: 'Classic Leather Derby',
    price: 179.0,
    category: 'footwear',
    rating: 4.7,
    reviewsCount: 44,
    image: svg('LEATHER DERBY', 'GOODYEAR WELT', '92400e', '451a03', 'd97706'),
    images: [],
    description: 'Elegant Derby shoe with full-grain leather upper and Goodyear welt.',
    specs: { 'Upper Material': 'Full-Grain Leather', 'Sole Material': 'Leather + Rubber', 'Closure': 'Lace-Up', 'Weight': '320g' },
    variations: { type: 'color', options: [{ name: 'Chestnut', value: '#92400e', active: true }, { name: 'Night Black', value: '#0f172a', active: false }] },
    featured: false,
    stock: 26,
    stockBySize: { '39': 1, '40': 3, '41': 5, '42': 8, '43': 4, '44': 2, '45': 1 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Leather with Rubber Heel',
    upperMaterial: 'Full-Grain Calfskin Leather',
  },
  {
    title: 'Eco-Friendly Canvas Sneakers',
    price: 89.0,
    category: 'footwear',
    rating: 4.5,
    reviewsCount: 39,
    image: svg('CANVAS SNKR', 'ECO FRIENDLY', '7b341e', '451a03', 'fdba74'),
    images: [],
    description: 'Lightweight canvas sneakers with recycled rubber soles and organic cotton lining.',
    specs: { 'Upper Material': 'Organic Canvas', 'Sole Material': 'Recycled Rubber', 'Closure': 'Lace-Up', 'Weight': '280g' },
    variations: { type: 'color', options: [{ name: 'Earth Brown', value: '#7b341e', active: true }, { name: 'Sky Blue', value: '#60a5fa', active: false }] },
    featured: false,
    stock: 38,
    stockBySize: { '39': 0, '40': 5, '41': 9, '42': 12, '43': 7, '44': 4, '45': 3 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Recycled Natural Rubber',
    upperMaterial: 'Organic Canvas',
  },
  {
    title: 'Luxury Velvet Loafers',
    price: 199.0,
    category: 'footwear',
    rating: 4.9,
    reviewsCount: 22,
    image: svg('VELVET LOAFER', 'HANDCRAFTED', '6d28d9', '4c1d95', 'c4b5fd'),
    images: [],
    description: 'Sumptuous velvet loafers with silk lining and hand-stitched detailing.',
    specs: { 'Upper Material': 'Velvet', 'Sole Material': 'Rubber', 'Closure': 'Slip-On', 'Weight': '315g' },
    variations: { type: 'color', options: [{ name: 'Royal Purple', value: '#6d28d9', active: true }, { name: 'Midnight Black', value: '#0f172a', active: false }] },
    featured: true,
    stock: 20,
    stockBySize: { '39': 1, '40': 2, '41': 4, '42': 6, '43': 3, '44': 2, '45': 1 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Flexible Rubber with Leather Insole',
    upperMaterial: 'Italian Velvet',
  },
  {
    title: 'Waterproof Hiking Boots',
    price: 175.0,
    category: 'footwear',
    rating: 4.8,
    reviewsCount: 94,
    image: svg('HIKING BOOT', 'WATERPROOF', '78350f', '422006', 'fbbf24'),
    images: [],
    description: 'Mid-cut waterproof hiking boots with Gore-Tex membrane and Vibram outsole.',
    specs: { 'Upper Material': 'Full-Grain Leather + Gore-Tex', 'Sole Material': 'Vibram Outsole', 'Closure': 'Speed-Lace', 'Weight': '520g' },
    variations: { type: 'color', options: [{ name: 'Earth Brown', value: '#78350f', active: true }, { name: 'Graphite', value: '#374151', active: false }] },
    featured: true,
    stock: 33,
    stockBySize: { '39': 2, '40': 5, '41': 7, '42': 10, '43': 4, '44': 3, '45': 2 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Vibram Multi-Terrain + EVA Midsole',
    upperMaterial: 'Full-Grain Leather with Gore-Tex Membrane',
  },
  {
    title: 'Minimalist Barefoot Sneaker',
    price: 110.0,
    category: 'footwear',
    rating: 4.6,
    reviewsCount: 67,
    image: svg('BAREFOOT', 'ZERO DROP', '475569', '1e293b', 'cbd5e1'),
    images: [],
    description: 'Zero-drop barefoot sneaker with wide toe box and flexible sole.',
    specs: { 'Upper Material': 'Knit Textile', 'Sole Material': 'Thin Rubber (5mm)', 'Drop': '0mm', 'Weight': '195g' },
    variations: { type: 'color', options: [{ name: 'Stone Grey', value: '#475569', active: true }, { name: 'Charcoal', value: '#1c1917', active: false }] },
    featured: false,
    stock: 40,
    stockBySize: { '39': 3, '40': 6, '41': 8, '42': 11, '43': 5, '44': 4, '45': 3 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: '5mm Natural Rubber',
    upperMaterial: 'Breathable Knit Textile',
  },
  {
    title: 'Chelsea Boots',
    price: 195.0,
    category: 'footwear',
    rating: 4.8,
    reviewsCount: 75,
    image: svg('CHELSEA BOOT', 'PREMIUM LEATHER', '1c1917', '0c0a09', 'a8a29e'),
    images: [],
    description: 'Classic Chelsea boots in burnished leather with elastic side panels.',
    specs: { 'Upper Material': 'Burnished Calfskin', 'Sole Material': 'Stacked Leather Heel', 'Closure': 'Elastic Side Panel', 'Weight': '440g' },
    variations: { type: 'color', options: [{ name: 'Burnished Black', value: '#1c1917', active: true }, { name: 'Tobacco', value: '#92400e', active: false }] },
    featured: true,
    stock: 28,
    stockBySize: { '39': 1, '40': 4, '41': 6, '42': 9, '43': 4, '44': 2, '45': 2 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Stacked Leather Heel with Rubber Top',
    upperMaterial: 'Burnished Calfskin Leather',
  },
  {
    title: 'Knit Running Shoes',
    price: 139.0,
    category: 'footwear',
    rating: 4.6,
    reviewsCount: 103,
    image: svg('KNIT RUNNER', 'ULTRA LIGHT', '0ea5e9', '0284c7', 'e0f2fe'),
    images: [],
    description: 'Ultra-lightweight knit running shoes with responsive foam midsole.',
    specs: { 'Upper Material': 'Flyknit Textile', 'Sole Material': 'React Foam', 'Drop': '10mm', 'Weight': '220g' },
    variations: { type: 'color', options: [{ name: 'Ocean Blue', value: '#0ea5e9', active: true }, { name: 'Volt Green', value: '#84cc16', active: false }] },
    featured: false,
    stock: 52,
    stockBySize: { '39': 4, '40': 7, '41': 10, '42': 14, '43': 8, '44': 5, '45': 4 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'React Foam Midsole + Rubber Outsole',
    upperMaterial: 'Engineered Flyknit',
  },
  {
    title: 'Monk Strap Dress Shoes',
    price: 229.0,
    category: 'footwear',
    rating: 4.8,
    reviewsCount: 33,
    image: svg('MONK STRAP', 'DOUBLE BUCKLE', '78350f', '451a03', 'd97706'),
    images: [],
    description: 'Double monk strap dress shoes in polished calfskin with antique brass buckles.',
    specs: { 'Upper Material': 'Polished Calfskin', 'Sole Material': 'Leather', 'Closure': 'Double Monk Strap', 'Weight': '350g' },
    variations: { type: 'color', options: [{ name: 'Cognac', value: '#78350f', active: true }, { name: 'Espresso', value: '#3f1f0a', active: false }] },
    featured: false,
    stock: 19,
    stockBySize: { '39': 1, '40': 2, '41': 4, '42': 6, '43': 3, '44': 2, '45': 1 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Full Leather Sole',
    upperMaterial: 'Mirror-Polished Calfskin',
  },
  {
    title: 'Platform Sneakers',
    price: 99.0,
    category: 'footwear',
    rating: 4.5,
    reviewsCount: 71,
    image: svg('PLATFORM', 'CHUNKY SOLE', 'e11d48', '9f1239', 'fda4af'),
    images: [],
    description: 'Chunky platform sneakers with 4cm elevated sole and premium leather upper.',
    specs: { 'Upper Material': 'Smooth Leather', 'Sole Material': 'EVA Platform (4cm)', 'Closure': 'Lace-Up', 'Weight': '380g' },
    variations: { type: 'color', options: [{ name: 'White/Pink', value: '#fda4af', active: true }, { name: 'Triple Black', value: '#0f172a', active: false }] },
    featured: false,
    stock: 35,
    stockBySize: { '36': 3, '37': 5, '38': 7, '39': 8, '40': 6, '41': 4, '42': 2 },
    ukSizes: [3, 4, 5, 6, 7, 8, 9],
    soleMaterial: 'EVA Foam Platform',
    upperMaterial: 'Smooth Leather',
  },
  {
    title: 'Retro Basketball Highs',
    price: 129.0,
    category: 'footwear',
    rating: 4.7,
    reviewsCount: 86,
    image: svg('RETRO HIGHS', 'BASKETBALL', 'dc2626', '991b1b', 'fca5a5'),
    images: [],
    description: 'Retro-inspired high-top basketball shoes with air-cushion heel unit.',
    specs: { 'Upper Material': 'Perforated Leather', 'Sole Material': 'Rubber + Air Cushion', 'Closure': 'Lace-Up', 'Weight': '370g' },
    variations: { type: 'color', options: [{ name: 'Varsity Red', value: '#dc2626', active: true }, { name: 'University Blue', value: '#2563eb', active: false }, { name: 'Triple White', value: '#f8fafc', active: false }] },
    featured: true,
    stock: 45,
    stockBySize: { '39': 3, '40': 6, '41': 9, '42': 12, '43': 7, '44': 5, '45': 3 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Rubber + Air Cushion Unit',
    upperMaterial: 'Perforated Full-Grain Leather',
  },
  {
    title: 'Woven Leather Sandals',
    price: 89.0,
    category: 'footwear',
    rating: 4.4,
    reviewsCount: 52,
    image: svg('WOVEN SANDAL', 'LEATHER', '92400e', '78350f', 'fdba74'),
    images: [],
    description: 'Hand-woven leather sandals with contoured cork footbed.',
    specs: { 'Upper Material': 'Hand-Woven Leather', 'Sole Material': 'Cork + Rubber', 'Closure': 'Adjustable Buckle', 'Weight': '240g' },
    variations: { type: 'color', options: [{ name: 'Tan', value: '#92400e', active: true }, { name: 'Dark Brown', value: '#451a03', active: false }] },
    featured: false,
    stock: 30,
    stockBySize: { '39': 2, '40': 4, '41': 6, '42': 8, '43': 5, '44': 3, '45': 2 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Cork Footbed + Rubber Outsole',
    upperMaterial: 'Hand-Woven Leather',
  },
  {
    title: 'Slip-On Mules',
    price: 95.0,
    category: 'footwear',
    rating: 4.6,
    reviewsCount: 46,
    image: svg('MULES', 'BACKLESS SLIP-ON', '5b21b6', '3b0764', 'd8b4fe'),
    images: [],
    description: 'Backless leather mules with padded insole and wooden heel.',
    specs: { 'Upper Material': 'Nappa Leather', 'Sole Material': 'Wooden Heel + Rubber Tip', 'Closure': 'Slip-On', 'Weight': '280g' },
    variations: { type: 'color', options: [{ name: 'Plum', value: '#5b21b6', active: true }, { name: 'Cream', value: '#fef9ef', active: false }] },
    featured: false,
    stock: 24,
    stockBySize: { '36': 2, '37': 3, '38': 5, '39': 6, '40': 4, '41': 3, '42': 1 },
    ukSizes: [3, 4, 5, 6, 7, 8, 9],
    soleMaterial: 'Wooden Heel with Rubber Tip',
    upperMaterial: 'Soft Nappa Leather',
  },
  {
    title: 'Espadrille Flats',
    price: 55.0,
    category: 'footwear',
    rating: 4.5,
    reviewsCount: 68,
    image: svg('ESPADRILLE', 'JUTE SOLE', 'f59e0b', 'b45309', 'fef3c7'),
    images: [],
    description: 'Classic espadrille flats with hand-stitched jute rope sole.',
    specs: { 'Upper Material': 'Organic Cotton Canvas', 'Sole Material': 'Jute Rope + Rubber', 'Closure': 'Slip-On', 'Weight': '180g' },
    variations: { type: 'color', options: [{ name: 'Mustard', value: '#f59e0b', active: true }, { name: 'Natural', value: '#fefce8', active: false }, { name: 'Navy', value: '#1e3a8a', active: false }] },
    featured: false,
    stock: 55,
    stockBySize: { '36': 5, '37': 7, '38': 10, '39': 12, '40': 8, '41': 7, '42': 6 },
    ukSizes: [3, 4, 5, 6, 7, 8, 9],
    soleMaterial: 'Hand-Stitched Jute + Rubber',
    upperMaterial: 'Organic Cotton Canvas',
  },
  {
    title: 'Steel-Toe Work Boots',
    price: 159.0,
    category: 'footwear',
    rating: 4.7,
    reviewsCount: 81,
    image: svg('WORK BOOT', 'STEEL TOE', '451a03', '1c0a00', 'a16207'),
    images: [],
    description: 'Heavy-duty steel-toe work boots with oil-resistant outsole. ASTM certified.',
    specs: { 'Upper Material': 'Full-Grain Leather', 'Sole Material': 'Oil-Resistant Rubber', 'Safety': 'Steel Toe, EH Rated', 'Weight': '680g' },
    variations: { type: 'color', options: [{ name: 'Wheat', value: '#a16207', active: true }, { name: 'Black', value: '#0f172a', active: false }] },
    featured: false,
    stock: 36,
    stockBySize: { '39': 2, '40': 5, '41': 7, '42': 10, '43': 5, '44': 4, '45': 3 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Oil-Resistant Rubber',
    upperMaterial: 'Full-Grain Waterproof Leather',
  },
  {
    title: 'Quilted Puffer Boots',
    price: 135.0,
    category: 'footwear',
    rating: 4.6,
    reviewsCount: 43,
    image: svg('PUFFER BOOT', 'INSULATED', '1e293b', '0f172a', '64748b'),
    images: [],
    description: 'Warm quilted puffer boots with Thinsulate insulation and fleece lining.',
    specs: { 'Upper Material': 'Quilted Nylon', 'Sole Material': 'EVA + Rubber', 'Insulation': 'Thinsulate 200g', 'Weight': '420g' },
    variations: { type: 'color', options: [{ name: 'Midnight', value: '#1e293b', active: true }, { name: 'Olive', value: '#365314', active: false }] },
    featured: false,
    stock: 28,
    stockBySize: { '36': 2, '37': 3, '38': 5, '39': 6, '40': 5, '41': 4, '42': 3 },
    ukSizes: [3, 4, 5, 6, 7, 8, 9],
    soleMaterial: 'EVA Midsole + Rubber Outsole',
    upperMaterial: 'Quilted Waterproof Nylon',
  },
  {
    title: 'Leather Boat Shoes',
    price: 115.0,
    category: 'footwear',
    rating: 4.5,
    reviewsCount: 59,
    image: svg('BOAT SHOES', 'CLASSIC DECK', '92400e', '78350f', 'd6d3d1'),
    images: [],
    description: 'Classic leather boat shoes with hand-sewn moccasin construction.',
    specs: { 'Upper Material': 'Full-Grain Leather', 'Sole Material': 'Non-Marking Rubber', 'Closure': '360 deg Lace', 'Weight': '290g' },
    variations: { type: 'color', options: [{ name: 'Sahara', value: '#92400e', active: true }, { name: 'Navy', value: '#1e3a8a', active: false }] },
    featured: false,
    stock: 32,
    stockBySize: { '39': 2, '40': 4, '41': 7, '42': 9, '43': 5, '44': 3, '45': 2 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Non-Marking Siped Rubber',
    upperMaterial: 'Full-Grain Boat Leather',
  },
  {
    title: 'Performance Tennis Shoes',
    price: 125.0,
    category: 'footwear',
    rating: 4.7,
    reviewsCount: 72,
    image: svg('TENNIS SHOE', 'COURT GRIP', 'f8fafc', 'e2e8f0', '1e40af', true),
    images: [],
    description: 'Court-specific tennis shoes with herringbone tread and toe drag guard.',
    specs: { 'Upper Material': 'Synthetic Leather + Mesh', 'Sole Material': 'Herringbone Rubber', 'Closure': 'Lace-Up', 'Weight': '310g' },
    variations: { type: 'color', options: [{ name: 'White/Blue', value: '#1e40af', active: true }, { name: 'All Black', value: '#0f172a', active: false }] },
    featured: false,
    stock: 38,
    stockBySize: { '39': 2, '40': 5, '41': 8, '42': 11, '43': 6, '44': 4, '45': 2 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Herringbone Non-Marking Rubber',
    upperMaterial: 'Synthetic Leather + Breathable Mesh',
  },
  {
    title: 'Suede Desert Boots',
    price: 145.0,
    category: 'footwear',
    rating: 4.6,
    reviewsCount: 55,
    image: svg('DESERT BOOT', 'SUEDE CLASSIC', 'a16207', '78350f', 'fde68a'),
    images: [],
    description: 'Iconic desert boots in brushed suede with crepe rubber sole.',
    specs: { 'Upper Material': 'Brushed Suede', 'Sole Material': 'Natural Crepe Rubber', 'Closure': '2-Eyelet Lace', 'Weight': '350g' },
    variations: { type: 'color', options: [{ name: 'Sand', value: '#a16207', active: true }, { name: 'Charcoal', value: '#374151', active: false }] },
    featured: false,
    stock: 29,
    stockBySize: { '39': 1, '40': 4, '41': 6, '42': 8, '43': 5, '44': 3, '45': 2 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Natural Crepe Rubber',
    upperMaterial: 'Brushed Suede Leather',
  },
  {
    title: 'Gore-Tex Rain Boots',
    price: 165.0,
    category: 'footwear',
    rating: 4.7,
    reviewsCount: 48,
    image: svg('RAIN BOOTS', 'GORE-TEX', '0c4a6e', '082f49', '67e8f9'),
    images: [],
    description: 'Fully waterproof Gore-Tex lined rain boots with thermal insulation.',
    specs: { 'Upper Material': 'Rubber + Gore-Tex Lining', 'Sole Material': 'Non-Slip Rubber', 'Height': 'Mid-Calf', 'Weight': '550g' },
    variations: { type: 'color', options: [{ name: 'Deep Navy', value: '#0c4a6e', active: true }, { name: 'Hunter Green', value: '#14532d', active: false }] },
    featured: false,
    stock: 25,
    stockBySize: { '36': 2, '37': 3, '38': 4, '39': 5, '40': 4, '41': 4, '42': 3 },
    ukSizes: [3, 4, 5, 6, 7, 8, 9],
    soleMaterial: 'Non-Slip Rubber',
    upperMaterial: 'Moulded Rubber + Gore-Tex',
  },
  {
    title: 'Wool-Lined Clogs',
    price: 79.0,
    category: 'footwear',
    rating: 4.4,
    reviewsCount: 63,
    image: svg('WOOL CLOGS', 'LINED', '059669', '064e3b', '6ee7b7'),
    images: [],
    description: 'Comfortable clogs with merino wool lining and contoured cork footbed.',
    specs: { 'Upper Material': 'Suede + Shearling', 'Sole Material': 'Cork + EVA', 'Closure': 'Slip-On', 'Weight': '270g' },
    variations: { type: 'color', options: [{ name: 'Moss', value: '#059669', active: true }, { name: 'Taupe', value: '#a8a29e', active: false }] },
    featured: false,
    stock: 42,
    stockBySize: { '36': 4, '37': 6, '38': 8, '39': 9, '40': 6, '41': 5, '42': 4 },
    ukSizes: [3, 4, 5, 6, 7, 8, 9],
    soleMaterial: 'Cork Footbed + EVA Outsole',
    upperMaterial: 'Suede with Shearling Lining',
  },
  {
    title: 'Cycling Road Shoes',
    price: 185.0,
    category: 'footwear',
    rating: 4.8,
    reviewsCount: 36,
    image: svg('CYCLING SHOE', 'CARBON SOLE', 'dc2626', '991b1b', 'fca5a5'),
    images: [],
    description: 'Stiff carbon-composite sole cycling shoes with BOA dial closure.',
    specs: { 'Upper Material': 'Microfibre + Mesh', 'Sole Material': 'Carbon Composite', 'Closure': 'BOA Dial', 'Weight': '245g' },
    variations: { type: 'color', options: [{ name: 'Racing Red', value: '#dc2626', active: true }, { name: 'Carbon Black', value: '#111827', active: false }] },
    featured: false,
    stock: 18,
    stockBySize: { '39': 1, '40': 2, '41': 4, '42': 5, '43': 3, '44': 2, '45': 1 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Full Carbon Composite',
    upperMaterial: 'Perforated Microfibre',
  },
  {
    title: 'Sheepskin Slippers',
    price: 65.0,
    category: 'footwear',
    rating: 4.7,
    reviewsCount: 107,
    image: svg('SLIPPERS', 'SHEEPSKIN', 'a8a29e', '78716c', 'f5f5f4'),
    images: [],
    description: 'Genuine sheepskin slippers with plush wool lining and indoor/outdoor sole.',
    specs: { 'Upper Material': 'Genuine Sheepskin', 'Sole Material': 'EVA Indoor/Outdoor', 'Closure': 'Slip-On', 'Weight': '210g' },
    variations: { type: 'color', options: [{ name: 'Stone', value: '#a8a29e', active: true }, { name: 'Chestnut', value: '#92400e', active: false }] },
    featured: false,
    stock: 60,
    stockBySize: { '36': 5, '37': 8, '38': 10, '39': 12, '40': 9, '41': 8, '42': 8 },
    ukSizes: [3, 4, 5, 6, 7, 8, 9],
    soleMaterial: 'EVA Indoor/Outdoor Sole',
    upperMaterial: 'Genuine Sheepskin',
  },
  {
    title: 'Brogue Wingtip Shoes',
    price: 215.0,
    category: 'footwear',
    rating: 4.8,
    reviewsCount: 42,
    image: svg('BROGUE WINGTIP', 'HAND-PUNCHED', '1c1917', '0c0a09', 'a8a29e'),
    images: [],
    description: 'Classic full-brogue wingtip shoes with hand-punched medallion toe.',
    specs: { 'Upper Material': 'Polished Calfskin', 'Sole Material': 'Leather + Rubber Heel', 'Construction': 'Goodyear Welt', 'Weight': '360g' },
    variations: { type: 'color', options: [{ name: 'Oxblood', value: '#7f1d1d', active: true }, { name: 'Midnight', value: '#0f172a', active: false }] },
    featured: true,
    stock: 21,
    stockBySize: { '39': 1, '40': 3, '41': 4, '42': 6, '43': 3, '44': 2, '45': 2 },
    ukSizes: [5, 6, 7, 8, 9, 10, 11],
    soleMaterial: 'Leather Sole + Rubber Heel Cap',
    upperMaterial: 'Polished Calfskin Leather',
  },
];


// Initial Mock Promo Codes
const promoCodesData = [
  {
    code: 'AURA10',
    discountPercent: 10,
    description: '10% off your order',
    active: true,
  },
  {
    code: 'SAVE20',
    discountPercent: 20,
    description: '20% off your order',
    active: true,
  },
];

const seedData = async () => {
  try {
    // Connect to database
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB for seeding.');

    // Clear existing products
    await Product.deleteMany();
    console.log('🧹 Cleared existing Products.');

    // Clear existing promo codes
    await PromoCode.deleteMany();
    console.log('🧹 Cleared existing Promo Codes.');

    // Insert new products
    const createdProducts = await Product.insertMany(productsData);
    console.log(`🌱 Seeded ${createdProducts.length} Products.`);

    // Insert new promo codes
    const createdPromos = await PromoCode.insertMany(promoCodesData);
    console.log(`🌱 Seeded ${createdPromos.length} Promo Codes.`);

    console.log('🎉 Seeding completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error(`❌ Seeding failed: ${error.message}`);
    process.exit(1);
  }
};

seedData();
